### ISSUE TITLE
website

### ISSUE THREAD

**Issue by mpmdean** [NSLS-II/edrixs#107]
There seems to be an issue with the website, although I cannot understand whether it is associated with our website code or with the host

If I go to
https://nsls-ii.github.io/edrixs/
and run a search via the box, the system seems to get stuck searching and never return results.

 @mrakitin could you take a took?

**Comment by mrakitin** [comment]
I don't know. Maybe a sphinx bug. @danielballan, have you encountered such an issue?

**Comment by mpmdean** [comment]
In case it helps with diagnosis, a local build of the website does have a functioning search.

**Comment by mpmdean** [comment]
Hi, @danielballan I'm just bouncing this question back. I get the feeling we're a bit stuck with this.

**Comment by mpmdean** [comment]
Hey @mrakitin are we stuck on this issue? Can we think of people who might be willing to help? Thanks!

**Comment by mrakitin** [comment]
I have a few guesses here:
- Python 3.6 used for the TravisCI configuration is too old, and had issues generating valid pages;
- the `sphinx_rtd_theme` package v0.5.0 might have been broken, so [v0.5.1](https://github.com/readthedocs/sphinx_rtd_theme/blob/master/docs/changelog.rst#v051) _may_ fix it.

I can't run TravisCI.org jobs now to check either guess, and the commercial version is not free / we've run out of free minutes. For other projects, we switched to the GitHub Actions for our CI needs. Check https://github.com/bluesky/bluesky/pull/1427 for details on how to migrate to that. It requires some effort, and If you need help from DAMA, please coordinate with @stuartcampbell.

**Comment by mrakitin** [comment]
Ah, a manual rerun (https://www.travis-ci.org/github/NSLS-II/edrixs/builds/758578397) seems to have fixed the issue!

![image](https://user-images.githubusercontent.com/13209176/107694788-c4005500-6c7d-11eb-81f3-7040f42b18e5.png)

**Comment by danielballan** [comment]
I somehow missed notifications for this. I have anecdotally observed sphinx search be slow on large documentation, but given @mrakitin this looks like a transient issue. Maybe the index didn't build right.

**Comment by mpmdean** [comment]
Thanks @mrakitin and @danielballan !

Great to have it working. I'm not knowledgeable enough to change the CI for the website build. At least not without a lot of reading, so I propose to keep an eye on this.  Hopefully, it won't be a reoccurring problem.

**Comment by mrakitin** [comment]
@mpmdean, you are welcome!

The CI change is not only relevant to this documentation issue, but to the general CI infrastructure. The .org version of TravisCI will be turned down in a few weeks, so we'd need to migrate to GitHub Actions soon.

**Comment by mpmdean** [comment]
@mrakitin 

I see. Maybe we should close this issue and open another on migrating to GitHub Actions. Realistically, I think we need DAMA's help to do this.

**Comment by mrakitin** [comment]
OK, sounds good. This specific one is resolved.
