### ISSUE TITLE
Migrate CI to GitHub Actions

### ISSUE THREAD

**Issue by mpmdean** [NSLS-II/edrixs#109]
travis-ci.org will be shutting down in several weeks

@mrakitin was suggesting that we migrate to GitHub Actions for our CI needs. Check bluesky/bluesky#1427 for details on how to migrate to that.

**Comment by stuartcampbell** [comment]
I did start to add some workflows a while ago... https://github.com/NSLS-II/edrixs/pull/68

**Comment by mrakitin** [comment]
Closed via #125.
