### ISSUE TITLE
Setup.py with python only option

### ISSUE THREAD

**Issue by Anselmoo** [NSLS-II/edrixs#113]
## Reason:
---
Working with a virtual environment like `poetry` or `pipenv` causes trouble / crashed during the installation as a result of missing links to the compiler.

## Future Feature 
--- 

Would it be possible to allow an option in the `setup.py` just to install the pure python code? No Fortran, no mpi4py

**Comment by mpmdean** [comment]
@Anselmoo thanks for the comment

I think the main issue is that
