### ISSUE TITLE
Summarising GitHub Action workflows

### ISSUE THREAD

**Issue by Anselmoo** [NSLS-II/edrixs#128]
* The workflows flake8, testing, and docs can be summarized in one pipeline. 
* `testing` can depend on `lint`, and `docs` on `testing`, which reduce computational time for non-merging-able PRs.

![image](https://user-images.githubusercontent.com/13209783/131555316-48bfbcba-e43f-419d-af89-04e52662aebe.png)

**Comment by mrakitin** [comment]
Closed via #129.
