### ISSUE TITLE
The GNU License is incomplete

### ISSUE THREAD

**Issue by Anselmoo** [NSLS-II/edrixs#130]
In the [COPYING](https://github.com/NSLS-II/edrixs/blob/master/COPYING) file author, name of `edrixs`, and year are not defined. 
Also, GitHub is linked just to [LICENSE](https://github.com/NSLS-II/edrixs/blob/master/LICENSE), which is a classical GNU and not GNU v3+ license.

Suggestion: 

* Copy the updated [COPYING](https://github.com/NSLS-II/edrixs/blob/master/COPYING) into [LICENSE](https://github.com/NSLS-II/edrixs/blob/master/LICENSE),
* Delete [COPYING](https://github.com/NSLS-II/edrixs/blob/master/COPYING)

https://github.com/NSLS-II/edrixs/blob/691b04c6a582f0ef361c34cda180f9745e94921a/COPYING#L634-L659

**Comment by mpmdean** [comment]
Fixed via #131
