### ISSUE TITLE
[ENH] Add CITATION.cff 

### ISSUE THREAD

**Issue by Anselmoo** [NSLS-II/edrixs#141]
Adding GitHub's `CITATION.cff` for linking repo to the [EDRIXS: An open source toolkit for simulating spectra of resonant inelastic x-ray scattering](https://www.sciencedirect.com/science/article/abs/pii/S0010465519301353?via%3Dihub)

[https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)

**Comment by mpmdean** [comment]
I wasn't aware of this feature. It would be great to include this. Would you be up for creating a PR?

**Comment by Anselmoo** [comment]
> I wasn't aware of this feature. It would be great to include this. Would you be up for creating a PR?

Sure!
