### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mpmdean** [NSLS-II/edrixs#148]
We should probably make another release as it has been a while and a non-negligible bug was discovered and corrected recently. 

@mrakitin I see that https://github.com/nsls-ii-forge/edrixs-feedstock has been archived, so I guess that the procedure for generating the conda package has changed?

**Comment by mrakitin** [comment]
Hi @mpmdean, during the summer of 2021 we moved mostly all feedstocks to `conda-forge`, however, due to some obstacles of building `arpack-mpi` (which is one of the `edrixs` dependencies), the `edrixs` feedstock is not in `conda-forge` yet. See https://github.com/conda-forge/staged-recipes/pull/15729#issuecomment-890171162 for the details. I don't currently have time to address it, but if you or some of your colleagues have the bandwidth, I can assist in getting it into the `conda-forge` channel.

**Comment by mpmdean** [comment]
Hi @mrakitin At our side, we are pretty badly limited by both skill and time in terms of solving a conda packaging issue solved. 

Is the former `nsls2-forge` method now broken or could it simply be unarchived as a temporary measure?

**Comment by mrakitin** [comment]
Let's try to unarchive the repo and rebuild it.

**Comment by mrakitin** [comment]
The unarchived feedstock did not work - I believe many underlying dependencies changed (OS version, compilers, etc.). We need to push on the conda-forge feedstocks.

**Comment by mpmdean** [comment]
That's a shame. Could you estimate when you might have time to look at this?

**Comment by mrakitin** [comment]
Hi @mpmdean, sorry for the delay. I may have some time in March to have the `arpack-mpi` integrated into the existing `arpack` conda-forge feedstock. I'll keep you posted here.

**Comment by mpmdean** [comment]
Thanks for that @mrakitin

**Comment by mrakitin** [comment]
Update: https://github.com/conda-forge/arpack-feedstock/pull/46 is a better implementation that was suggested by the conda-forge reviewer in https://github.com/conda-forge/arpack-feedstock/pull/45. Once it's reviewed -> merged -> built -> published in the conda-forge channel -> indexed, I'll work on the edrixs feedstock.

**Comment by danielballan** [comment]
Thank you, @mrakitin!

**Comment by mpmdean** [comment]
Thanks @mrakitin !

**Comment by mrakitin** [comment]
https://github.com/conda-forge/staged-recipes/pull/20438 is for the edrixs-feedstock. Hopefully, it can be merged soon. I had to fix the `arpack` package a bit to enable the right selection of the MPI-enabled package, and it solved the issue with `edrixs`. Now the tests are passing, including no-MPI and MPI execution of example 2.

@mpmdean, I listed you as a maintainer of the package. Please write in that PR that you are agreeing to co-maintain the feedstock (if you are 😄). Thanks!

**Comment by mpmdean** [comment]
@mrakitin I just wrote that I will help co-maintain.

**Comment by mrakitin** [comment]
Sounds great! No major work is expected there once the feedstock is live. We will work together on packaging it with CMake from another PR, but normally the maintainers only need to merge the auto-generated PRs for new versions with little to no intervention. I hope it works.

**Comment by mrakitin** [comment]
https://github.com/conda-forge/edrixs-feedstock is live now!

The package is in the conda-forge channel already:
![image](https://user-images.githubusercontent.com/13209176/190483872-6bb8139e-5dc4-46cf-a8ac-f625ad5e640d.png)

We need to wait until it's indexed, and then it can be used for testing and inclusion into the scipy-binder environments.

Then a new release will be easy to handle.

Final step: open a bottle of champagne to celebrate! 🍾 🎉

**Comment by mpmdean** [comment]
Thanks @mrakitin !

I was already able to install via conda-forge!

**Comment by mrakitin** [comment]
Good to hear that, @mpmdean!

The package was added to the scipy-binder environment: https://github.com/NSLS-II/scipy-binder/pull/41. I hope it can be pushed to JupyterHub soon.

Feel free to cut a new release. It has been a while without releases for this project.
After the things are tagged, we'll look at the CMake-based building.

**Comment by danielballan** [comment]
This is deployed to JupyterHub in the "beta software environment". It will move to the default environment in about a week.

**Comment by mpmdean** [comment]
Thanks mainly to @mrakitin this is now all sorted so I will close this.
