### ISSUE TITLE
Leaving note from Gilberto until this is fixed

### ISSUE THREAD

**Issue by mpmdean** [NSLS-II/edrixs#64]
Yilin and Mark: John and I noticed that there is an error in the atomic database for Ti. The Slater integrals for Fdd’s of the 3d1 and 3d0 configurations are non-zero in the database. I believe this doesn’t make a difference in the calculation, but it may be good to correct it anyway.

**Comment by shenmidelin** [comment]
This is not an error. I just gave some default values for 3d0, 3d1. They will not make a difference for the calculations. So just keep them. The users should not worry about it. I will close this issue #64.
