### ISSUE TITLE
Enable macOS conda packages

### ISSUE THREAD

**Issue by stuartcampbell** [NSLS-II/edrixs#69]
This is a tracking ticket to pull together tasks to enable macOS builds for edrixs.

List of PRs into the relevant feedstocks:

- [ ] https://github.com/nsls-ii-forge/arpack-mpi-feedstock/pull/3

- [ ] https://github.com/nsls-ii-forge/edrixs-feedstock/pull/7

**Comment by mpmdean** [comment]
We now have working macOS builds!

**Comment by mrakitin** [comment]
Enabled via https://github.com/conda-forge/edrixs-feedstock/pull/6.
