### ISSUE TITLE
GPL License 

### ISSUE THREAD

**Issue by shenmidelin** [NSLS-II/edrixs#7]
@NSLS-II/edrixs-team , Hi all, the paper of edrixs code (https://arxiv.org/pdf/1812.05735.pdf) 
 has been accepted as publication in CPC, I am now modifying it to submit a second version. The original version is based on the repo on my account, so I want to modify it based on the new repo under NSLS-II.  One issue is the license, GPL license is required for the codes developed in the COMSCOPE center (https://www.bnl.gov/comscope/software/index.php), so could we still use GPL license for projects under NSLS-II ?

**Comment by mrakitin** [comment]
I think it's fine, but I'd like to double-check with @stuartcampbell, @tacaswell and @danielballan.

**Comment by danielballan** [comment]
No problem. I see that [the original project was distributed under GPL](https://github.com/shenmidelin/edrixs/blob/master/LICENSE) and I can't see a reason why moving it to the NSLS-II org should require a change in license.

**Comment by mrakitin** [comment]
@shenmidelin, feel free to submit a pull request with the update.
